name: main 브랜치 S3에 배포하기

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 레포지토리 파일 불러오기
        uses: actions/checkout@v5

      - name: 의존성 설치하기
        run: npm install

      - name: 빌드하기
        run: npm run build

      - name: AWS 인증 설정
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: S3 버킷 비우기
        run: aws s3 rm --recursive s3://oz-aws-git-flow

      - name: S3 버킷에 프로젝트 업로드하기
        run: aws s3 cp --recursive ./dist s3://oz-aws-git-flow

      - name: CloudFront 캐시 무효화하기
        run: |
          aws cloudfront create-invalidation \
          --distribution-id E1N9XP9CN4HY9B \
          --paths "/*"
